<h1 style="color:yellow"><b>Numpy</b></h1>

In [3]:
import numpy as np

In [4]:
print("Hello")

Hello


In [5]:
myarray = np.array([1,2,3,4,5])

In [6]:
myarray

array([1, 2, 3, 4, 5])

In [7]:
a = np.array([2, 444, 66, 2, 7], np.int64)

In [8]:
a

array([  2, 444,  66,   2,   7])

np.int64, np.int32 etc used for size allocation

In [7]:
a[0]

np.int64(2)

In [8]:
a.shape

(5,)

In [9]:
b = np.array([[3,4,6,8]], np.int32)

In [10]:
b

array([[3, 4, 6, 8]], dtype=int32)

In [11]:
b.shape

(1, 4)

Here (1,4) means 1 row and 4 columns

In [12]:
b[0,0]

np.int32(3)

Showing the value of 0 th row and 0th col value

In [14]:
b.dtype

dtype('int32')

shows the type of the data

<h4> For type references: <a href="https://numpy.org/doc/2.1/reference/arrays.dtypes.html">Type references</a> </h4>

# Array Creation: Conversion From Other Python Structures

In [15]:
listarray = np.array([[2,4,5], [5, 7, 65], [1,45,6]])

In [16]:
listarray

array([[ 2,  4,  5],
       [ 5,  7, 65],
       [ 1, 45,  6]])

In [17]:
listarray.shape

(3, 3)

In [18]:
listarray.size

9

In [19]:
listarray.dtype

dtype('int64')

In [20]:
np.array({3,5,6})

array({3, 5, 6}, dtype=object)

In [21]:
zeros = np.zeros((2,4))

In [22]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Creates a 2,4 sized array of 0s

In [23]:
rng = np.arange(10)

In [24]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

***creates an array from 0 to (n-1)***

In [9]:
lspace1 = np.linspace(1,4,4)

In [10]:
lspace1

array([1., 2., 3., 4.])

In [11]:
lspace2 = np.linspace(1,5,4)

In [12]:
lspace2

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [13]:
arr = np.arange(15)

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [15]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

<h2><b>Numpy Axis</b></h2>

In [17]:
x = [ [1,2,3], [4,5,6], [7,1,0] ]

In [18]:
arr = np.array(x)

In [19]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [21]:
arr.sum(axis=0)

array([12,  8,  9])

Here axis = 0 means the arrow is pointing down, so
we get the sum of (1,4,7), (2,3,1)... 

In [22]:
arr.sum(axis=1)

array([ 6, 15,  8])

Here, axis = 1 means left to right, and we get the sum row wise

In [23]:
arr.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

Transposes the array

In [24]:
arr.flat

In [25]:
for item in arr.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [26]:
arr.ndim

2

ndim -> number of dimension

In [27]:
arr.size

9

In [28]:
arr.nbytes

72

returns total bytes consumed by the array

In [31]:
brr = np.array([34, 56, 7, -3, 5])

In [32]:
brr.argmax()

np.int64(1)

returns the idx of max elem

In [33]:
brr.argmin()

np.int64(3)

In [34]:
brr.argsort()

array([3, 4, 2, 0, 1])

returns idx of the sorted array (how it will be sorted)

In [35]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [36]:
arr.argmax()

np.int64(6)

In [37]:
arr.argmin()

np.int64(8)

In [38]:
arr.argmax(axis = 0)

array([2, 1, 1])

In [39]:
arr.argmax(axis = 1)

array([2, 2, 0])

In [41]:
arr1 = np.array([[1, 0, 3], [1, 1, 1], [0, 3, 2]])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [43]:
arr1

array([[1, 0, 3],
       [1, 1, 1],
       [0, 3, 2]])

In [44]:
arr + arr1

array([[2, 2, 6],
       [5, 6, 7],
       [7, 4, 2]])

In [46]:
arr * arr1

array([[1, 0, 9],
       [4, 5, 6],
       [0, 3, 0]])

In [47]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [48]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [50]:
np.where(arr > 5)

(array([1, 2]), array([2, 0]))

return tupple (row & col) where u can find the element

In [51]:
np.count_nonzero(arr)

8

<h2>Size of Array VS Numpy Array</h2>

In [52]:
import sys

In [53]:
py_ar = [1, 2, 3, 4]

In [54]:
np_ar = np.array(py_ar)

In [55]:
sys.getsizeof(1) * len(py_ar)

112

In [57]:
np_ar.itemsize * np_ar.size

32

<h3><i>For more attributes <a href = "https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html">Numpy Attributes</a></i></h3>